#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate individual UPDATE statements for week_plan
"""

import json
import os
import sys

# Force UTF-8 output
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

SYSTEM_ID = '9da7c347-fe63-4c81-81e1-df576bcd2e6c'

def load_metadata():
    """Load the metadata JSON file"""
    json_path = os.path.join(os.path.dirname(__file__), '..', '..', 'icarus_projects_metadata.json')
    with open(json_path, 'r', encoding='utf-8') as f:
        return json.load(f)

def normalize_text(text):
    """Normalize Chinese punctuation to ASCII"""
    if not text:
        return ''
    return (text
        .replace('"', '"').replace('"', '"')
        .replace(''', "'").replace(''', "'")
        .replace('—', '-').replace('–', '-')
    )

def build_week_plan(project):
    """Build simplified week_plan JSONB array"""
    weeks = project.get('weeks', [])
    week_plan = []

    for week in weeks:
        # Simplified structure - only essential info
        week_obj = {
            'week': week.get('week_number', 0),
            'theme': normalize_text(week.get('week_title', '')),
            'goals': normalize_text(week.get('week_objectives', '')),
            'day_count': len(week.get('days', []))
        }
        week_plan.append(week_obj)

    return week_plan

def escape_sql_string(s):
    """Escape single quotes for SQL"""
    return s.replace("'", "''")

def main():
    data = load_metadata()
    projects = data['projects']

    output_file = os.path.join(os.path.dirname(__file__), 'update_week_plans.sql')

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(f"-- Updating week_plan for {len(projects)} projects\n")
        f.write(f"-- Generated by gen_week_plan_sql.py\n\n")

        for idx, project in enumerate(projects, 1):
            stage_number = idx
            week_plan = build_week_plan(project)

            # Convert to JSON string
            week_plan_json = json.dumps(week_plan, ensure_ascii=False, indent=None)
            week_plan_escaped = escape_sql_string(week_plan_json)

            f.write(f"-- Project {stage_number}: {project['stage_name']}\n")
            f.write(f"UPDATE course_contents\n")
            f.write(f"SET week_plan = '{week_plan_escaped}'::jsonb,\n")
            f.write(f"    updated_at = NOW()\n")
            f.write(f"WHERE system_id = '{SYSTEM_ID}'::uuid\n")
            f.write(f"  AND sequence_number = {stage_number};\n\n")

    print(f"✓ Generated SQL file: {output_file}")
    print(f"✓ Total projects: {len(projects)}")

if __name__ == '__main__':
    main()
