#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate SQL to update course_contents with COMPLETE week_plan data (including goals and activities)
"""

import json
import os
import sys

# Force UTF-8 output
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

SYSTEM_ID = '9da7c347-fe63-4c81-81e1-df576bcd2e6c'

def load_metadata():
    """Load the metadata JSON file"""
    json_path = r'D:\CursorWork\FutureMindInstitute\icarus_projects_metadata.json'
    with open(json_path, 'r', encoding='utf-8') as f:
        return json.load(f)

def normalize_text(text):
    """Normalize Chinese punctuation to ASCII"""
    if not text:
        return ''
    return (text
        .replace('"', '"').replace('"', '"')
        .replace(''', "'").replace(''', "'")
        .replace('—', '-').replace('–', '-')
    )

def build_full_week_plan(project):
    """Build COMPLETE week_plan with goals and activities"""
    weeks = project.get('weeks', [])
    week_plan = []

    for week in weeks:
        # Extract goals from week_objectives
        goals_text = normalize_text(week.get('week_objectives', ''))
        goals = [g.strip() for g in goals_text.split('。') if g.strip() and len(g.strip()) > 3]
        if not goals:
            goals = ['完成本周学习任务']

        # Build activities from days
        activities = []
        for day in week.get('days', []):
            activity = {
                'day': day.get('day', ''),
                'title': normalize_text(day.get('title', '')),
                'duration': day.get('duration', ''),
                'description': normalize_text(day.get('description', ''))[:800]  # Limit length
            }
            activities.append(activity)

        week_obj = {
            'week': week.get('week_number', 0),
            'theme': normalize_text(week.get('week_title', '')),
            'goals': goals[:5],  # Limit to 5 goals
            'activities': activities
        }
        week_plan.append(week_obj)

    return week_plan

def escape_sql_string(s):
    """Escape single quotes for SQL"""
    return s.replace("'", "''").replace('\\', '\\\\')

def main():
    data = load_metadata()
    projects = data['projects']

    output_file = os.path.join(os.path.dirname(__file__), 'update_full_week_plans.sql')

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(f"-- Updating COMPLETE week_plan for {len(projects)} projects\n")
        f.write(f"-- Generated by generate_full_week_plans.py\n")
        f.write(f"-- Includes: week number, theme, goals, and detailed activities\n\n")

        for idx, project in enumerate(projects, 1):
            stage_number = idx
            week_plan = build_full_week_plan(project)

            # Convert to JSON string
            week_plan_json = json.dumps(week_plan, ensure_ascii=False, separators=(',', ':'))
            week_plan_escaped = escape_sql_string(week_plan_json)

            f.write(f"-- Project {stage_number}: {project['stage_name']}\n")
            f.write(f"UPDATE course_contents\n")
            f.write(f"SET week_plan = '{week_plan_escaped}'::jsonb,\n")
            f.write(f"    updated_at = NOW()\n")
            f.write(f"WHERE system_id = '{SYSTEM_ID}'::uuid\n")
            f.write(f"  AND sequence_number = {stage_number};\n\n")

            # Print summary
            print(f"✓ Project {stage_number}: {project['stage_name']}")
            print(f"   Weeks: {len(week_plan)}")
            for week in week_plan:
                print(f"     Week {week['week']}: {week['theme']}")
                print(f"       - Goals: {len(week['goals'])}")
                print(f"       - Activities: {len(week['activities'])}")

    print(f"\n✓ Generated SQL file: {output_file}")
    print(f"✓ Total projects: {len(projects)}")
    print(f"\nNext: Execute this SQL via Supabase MCP tool")

if __name__ == '__main__':
    main()
